# seahorse.prelude: the basis for writing Seahorse programs.
#
# NOTE: this file just contains types and documentation for your editor. This
# is NOT executable code, and you won't be able to change the behavior of your
# Seahorse programs by editing this file.

from typing import *

from num import *
from complexTypes import *
from anchor import *

# ================
# Helper functions
# ================

def declare_id(id: str):
    """Inform Anchor what this program's ID is.

    @param id: The program's ID, generated by Anchor in /target/idl/<program>.json. This must be copied-pasted straight from there as a string literal.
    """

def instruction(function: Callable[..., None]) -> Callable[..., None]:
    """Decorator to turn a function into a program instruction."""

def dataclass(function: Callable[..., None]) -> Callable[..., None]:
    """Decorator to create an automatic default class constructor."""

def int_bytes(n: Any, be: bool = False) -> List[u8]:
    """
    Convenience method to turn an integer type into a little-endian (by default) list of bytes.
    
    @param n: The integer you wish to convert to bytes.
    @param be: Whether you want the conversion to be big-endian - defaults to false.
    """

def size(ob: str) -> u64:
    """
    Get the size of an object in bytes.
    Currently this is only supported for strings.
    
    @param ob: The object to get the size of.
    """